version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/demo_website?schema=public
      - JWT_SECRET=your-super-secret-key-change-in-production
      - PORT=3001
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=demo_website
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
